services:
  - type: web
    name: Traffic_render1
    env: node
    plan: free
    buildCommand: npm install --prefer-offline --no-audit --no-fund
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
    healthCheckPath: /health
    autoDeploy: true
